/*
 * This file is the main driver for the Midnight bulletin board example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import {
  AuctionAPI,
  type AuctionDerivedState,
  type AuctionProviders,
  type DeployedAuctionContract,
  type PrivateStates,
  utils,
} from '@midnight-ntwrk/auction-api';
import { ledger, type Ledger, STATE } from '@midnight-ntwrk/auction-contract';
import { type ContractAddress } from '@midnight-ntwrk/compact-runtime';
import { type CoinInfo, nativeToken, Transaction, type TransactionId } from '@midnight-ntwrk/ledger';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { getLedgerNetworkId, getZswapNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import {
  type BalancedTransaction,
  createBalancedTx,
  type MidnightProvider,
  type UnbalancedTransaction,
  type WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { toHex } from '@midnight-ntwrk/midnight-js-utils';
import { type Resource, WalletBuilder } from '@midnight-ntwrk/wallet';
import { type Wallet } from '@midnight-ntwrk/wallet-api';
import { Transaction as ZswapTransaction } from '@midnight-ntwrk/zswap';
import { webcrypto } from 'crypto';
import { stdin as input, stdout as output } from 'node:process';
import { createInterface, type Interface } from 'node:readline/promises';
import { type Logger } from 'pino';
import * as Rx from 'rxjs';
import type { DockerComposeEnvironment, StartedDockerComposeEnvironment } from 'testcontainers';
import { WebSocket } from 'ws';
import { type Config, StandaloneConfig } from './config.js';
import SDK from "@hyperledger/identus-edge-agent-sdk";
import {
  sha512
} from '@noble/hashes/sha512'

import InMemory from '@pluto-encrypted/inmemory';

//globalThis.crypto = webcrypto;
if (!globalThis.crypto) {
  // @ts-ignore - TypeScript might complain about this
  // @ts-expect-error: It's needed to make Scala.js and WASM code able to use cryptography
  globalThis.crypto = webcrypto;
}

//globalThis.WebSocket = WebSocket;
if (!globalThis.WebSocket) {
  // @ts-ignore - TypeScript might complain about this
  // @ts-expect-error: It's needed to make Scala.js and WASM code able to use cryptography
  globalThis.WebSocket = WebSocket;
}

/* **********************************************************************
 * getAuctionLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific bulletin board contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the bulletin board contract.
 */



class ShortFormDIDResolverSample {
  method = "prism";

  async resolve(didString:string) {
      const url = "http://localhost:8085/cloud-agent/dids/" + didString;
      const response = await fetch(url, {
          method: "GET",
          mode: "cors",
          credentials: "omit"
      });

      if (!response.ok) {
          throw new Error('Failed to fetch data');
      }

      const data = await response.json();
      const didDocument = data.didDocument;

      const servicesProperty = new SDK.Domain.Services(didDocument.service);
      const verificationMethodsProperty = new SDK.Domain.VerificationMethods(didDocument.verificationMethod);
      const coreProperties = [];
      const authenticate = [];
      const assertion = [];

      for (const verificationMethod of didDocument.verificationMethod) {
          const isAssertion = didDocument.assertionMethod.find((method:any) => method === verificationMethod.id);
          if (isAssertion) {
              assertion.push(new SDK.Domain.AssertionMethod([isAssertion], [verificationMethod]));
          }
          const isAuthentication = didDocument.authentication.find((method:any) => method === verificationMethod.id);
          if (isAuthentication) {
              authenticate.push(new SDK.Domain.Authentication([isAuthentication], [verificationMethod]));
          }
      }

      coreProperties.push(...authenticate);
      coreProperties.push(servicesProperty);
      coreProperties.push(verificationMethodsProperty);

      const resolved = new SDK.Domain.DIDDocument(
          SDK.Domain.DID.fromString(didString),
          coreProperties
      );

      return resolved;
  }
}

async function getCredential(): Promise<SDK.Domain.Credential> {
  return new Promise(async (resolve, reject) => {
      const registerPrismDid = await fetch(`http://localhost:8085/cloud-agent/did-registrar/dids`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
              "documentTemplate": {
                  "publicKeys": [
                  {
                    "id": "auth-1",
                    "purpose": "authentication",
                    "curve":"secp256k1"
                  },
                  {
                    "id": "issue-1",
                    "purpose": "assertionMethod",
                    "curve":"secp256k1"
                  }
                ],
                "services": []
              }
          })
      });
      const prismDidResponse = await registerPrismDid.json();
      console.log('Prism DID created:', { longFormDid: prismDidResponse.longFormDid });
  
      const publishPrismDid = await fetch(`http://localhost:8085/cloud-agent/did-registrar/dids/${prismDidResponse.longFormDid}/publications`, {
          method: "POST",
          headers: { "Content-Type": "application/json" }
      });
      const publishResponse = await publishPrismDid.json();
      console.log('DID Published:', { operation: publishResponse.scheduledOperation });
  
      const createCredentialSchema = await fetch("http://localhost:8085/cloud-agent/schema-registry/schemas", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
              "name": "medical-prescription-schema-2b754046-32c6-42e0-b587-b28013422778",
              "version": "2.0.0",
              "description": "Medical Prescription Schema",
              "type": "https://w3c-ccg.github.io/vc-json-schemas/schema/2.0/schema.json",
              "author": `${publishResponse.scheduledOperation?.didRef}`,
              "tags": [
                  "driving",
                  "license"
              ],
              "schema": {
                  "$id": "https://example.com/medical-prescription-1.0.0",
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "description": "Medical Prescription ",
                  "type": "object",
                  "properties": {
                      "patientId": {
                          "type": "string",
                      },
                      "patientName": {
                          "type": "string"
                      },
                      "patientFamilyName": {
                          "type": "string"
                      },
                      "prescriptionId": {
                          "type": "string"
                      },
                      "dateOfIssuance": {
                          "type": "string",
                          "format": "date-time"
                      }
                  },
                  "required": [
                      "patientId",
                      "patientName",
                      "patientFamilyName",
                      "prescriptionId",
                      "dateOfIssuance"
                  ],
                  "additionalProperties": false
              }
          })
      });
      const schemaResponse = await createCredentialSchema.json();
      console.log('Schema Created:', { schemaId: schemaResponse.id });
  
      const getMediatorDid = await fetch("http://localhost:8080/did", {
          method: "GET",
          headers: {
              "Content-Type": "application/json"
          }
      });
      const mediatorDID = SDK.Domain.DID.fromString(await getMediatorDid.text());
      console.log('Mediator DID:', {
          did: mediatorDID
      });
  
      const hashedPassword = sha512("123456")
      const apollo = new SDK.Apollo();
      const store = new SDK.Store({
          name: "test",
          storage: InMemory as any,
          password: Buffer.from(hashedPassword).toString("hex")
      });
      const defaultSeed = apollo.createRandomSeed().seed // Random or custom seed u want to create
      const extraResolvers = [
          ShortFormDIDResolverSample
      ];
      const castor = new SDK.Castor(apollo, extraResolvers)
      const agent = await SDK.Agent.initialize({
          apollo,
          castor,
          mediatorDID,
          pluto: new SDK.Pluto(store, apollo),
          seed: defaultSeed
      });
  
      let credential;
      let presentationId;
      agent.addListener(SDK.ListenerKey.MESSAGE, async (messages:any) => {
          for (const message of messages) {
              if (message instanceof SDK.Domain.Message) {
                  if (message.piuri === SDK.ProtocolType.DidcommOfferCredential) {
                      /** 
                       * DIDComm Offer Credential Message
                       * Specification: https://didcomm.org/issue-credential/3.0/offer-credential
                       * Description: The credential offer contains a preview of the SDJWT credential and would inform
                       * you on what fields your credential will have.
                       * Offers must be manually accepted, and this is done by creating a Credential Request and sending it to the Cloud Agent
                       */
                      console.log('Credential Offer:', message);
                      const credentialOffer = SDK.OfferCredential.fromMessage(message);
                      const requestCredential = await agent.prepareRequestCredentialWithIssuer(credentialOffer);
                      const requestMessage = requestCredential.makeMessage()
                      await agent.sendMessage(requestMessage);
                  } else if (message.piuri === SDK.ProtocolType.DidcommIssueCredential) {
                      /** 
                       * DIDComm Issue Credential Message
                       * Specification: https://didcomm.org/issue-credential/3.0/issue-credential
                       * Description: This is the Issued Credential which gets stored inside the Identus Storage for later use.
                       */
                      console.log('Credential Issue:', message);
                      const attachment = message.attachments.at(0)
                      if (attachment) {
                          const encodedCompactSDJWT = attachment.payload;
                          credential = SDK.SDJWTCredential.fromJWS(encodedCompactSDJWT);
                          return resolve(credential)
                      }
                  } 
              }
          }
      });
  
      await agent.start()
  
      const getCredentialOffer = await fetch("http://localhost:8085/cloud-agent/issue-credentials/credential-offers/invitation", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
              "goalCode": "issue-vc",
              "goal": "To Issue a Medical Prescription Credential",
              "issuingDID": publishResponse.scheduledOperation?.didRef,
              "validityPeriod": 3600,
              "automaticIssuance": true,
              "credentialFormat": "JWT",
              "claims": {
                  "patientId": "#d4aab32e1",
                  "patientName": "Alice",
                  "patientFamilyName": "Wonderland",
                  "prescriptionId": "42344211134",
                  "dateOfBirth": "2020-11-13T20:20:39+00:00"
              }
          })
      });
      const credentialOfferResponse = await getCredentialOffer.json();
      console.log('Credential Offer:', { invitationUrl: credentialOfferResponse.invitation.invitationUrl });
      const parsed = await agent.parseOOBInvitation(new URL(credentialOfferResponse.invitation.invitationUrl));
      await agent.acceptInvitation(parsed, 'SampleCredentialOfferOOB');
  })
}

export const getAuctionLedgerState = (
  providers: AuctionProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> =>
  providers.publicDataProvider
    .queryContractState(contractAddress)
    .then((contractState) => (contractState != null ? ledger(contractState.data) : null));

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new auction contract
  2. Join an existing auction contract
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (providers: AuctionProviders, rli: Interface, logger: Logger): Promise<AuctionAPI | null> => {
  let api: AuctionAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        const item_description = await rli.question("What is item description? ");
        const minimum_bid = BigInt(await rli.question("What is the minimum bid? "));
        const bid_increment = BigInt(await rli.question("What is the bid increment? "));
        const reserve_price = BigInt(await rli.question("What is the reserve price at which the auction is automatically concluded? "));

        try {
          const credential = await getCredential();
          api = await AuctionAPI.deploy(providers, [item_description, minimum_bid, bid_increment, reserve_price],credential, logger);
          logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
          return api;
        } catch (error) {
          logger.error(`Failed to deploy the contract: ${error}`);
          break;
        }
      case '2':
        try {
          const credential = await getCredential();
          api = await AuctionAPI.join(
            providers, 
            await rli.question('What is the contract address (in hex)? '), 
            credential, 
            logger
          );
          logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
          return api;
        } catch (error) {
          logger.error(`Failed to join the contract: ${error}`);
          break;
        }
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the bulletin board.
 */

const displayLedgerState = async (
  providers: AuctionProviders,
  deployedAuctionContract: DeployedAuctionContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedAuctionContract.deployTxData.public.contractAddress;
  const ledgerState = await getAuctionLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no auction contract deployed at ${contractAddress}`);
  } else {
    const auctionState = ledgerState.auctionState === STATE.concluded ? 'concluded' : 'opened';
    const currentBid = ledgerState.currentBid.is_some ? ledgerState.currentBid.value : 'none';
    const currentBidder = ledgerState.currentBidder.is_some ? toHex(ledgerState.currentBidder.value) : 'none';
    logger.info(`Auction state: '${auctionState}'`);
    logger.info(`Item description is: '${ledgerState.itemDescription}'`);
    logger.info(`Minimum bid is: '${ledgerState.minimumBid}'`);
    logger.info(`Bid increment is: '${ledgerState.bidIncrement}'`);
    logger.info(`Current bid is: '${currentBid}'`);
    logger.info(`Current bidder is: '${currentBidder}'`);
    logger.info(`Reserve price is: '${ledgerState.reservePrice}'`);
    logger.info(`Item seller is: '${toHex(ledgerState.itemSeller)}'`);
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key.
 */

const displayPrivateState = async (providers: AuctionProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get('auctionPrivateState');
  if (privateState === null) {
    logger.info(`There is no existing bulletin board private state`);
  } else {
    logger.info(`Current secret key is: ${toHex(privateState.secretKey)}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state compares the poster key with the private secret key to
 * determine if the current user is the poster of the current message.
 */

const displayDerivedState = (ledgerState: AuctionDerivedState | undefined, logger: Logger) => {
  if (ledgerState === undefined) {
    logger.info(`No bulletin board state currently available`);
  } else {
    const auctionState = ledgerState.auction_state === STATE.concluded ? 'concluded' : 'opened';
    const currentBidder = ledgerState.current_bidder ? toHex(ledgerState.current_bidder) : 'none';
    logger.info(`Auction state: '${auctionState}'`);
    logger.info(`Item description is: '${ledgerState.item_description}'`);
    logger.info(`Minimum bid is: '${ledgerState.minimum_bid}'`);
    logger.info(`Bid increment is: '${ledgerState.bid_increment}'`);
    logger.info(`Current bid is: '${ledgerState.current_bid}'`);
    logger.info(`Current bidder is: '${currentBidder}'`);
    logger.info(`Reserve price is: '${ledgerState.reserve_price}'`);
    logger.info(`Item seller is: '${toHex(ledgerState.item_seller)}'`);
    logger.info(`Item seller is: '${ledgerState.isSeller ? 'you' : 'not you'}'`);
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the bulletin board CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Place a bid
  2. Conclude the auction with the current bid
  3. Display the current ledger state (known by everyone)
  4. Display the current private state (known only to this DApp instance)
  5. Display the current derived state (known only to this DApp instance)
  6. Exit
Which would you like to do? `;

const mainLoop = async (providers: AuctionProviders, rli: Interface, logger: Logger): Promise<void> => {
  const auctionApi = await deployOrJoin(providers, rli, logger);
  if (auctionApi === null) {
    return;
  }
  let currentState: AuctionDerivedState | undefined;
  const stateObserver = {
    next: (state: AuctionDerivedState) => (currentState = state),
  };
  const subscription = auctionApi.state$.subscribe(stateObserver);
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      switch (choice) {
        case '1': {
          const answer = await rli.question(`What price would you like to set for your bid? `);
          try {
            await auctionApi.placeBid(BigInt(answer));
          } catch (error) {
            logger.error(`Failed to place bid: ${error}`);
          }
          break;
        }
        case '2':
          try {
            await auctionApi.concludeAuction();
          } catch (error) {
            logger.error(`Failed to conclude bid: ${error}`);
          }
          break;
        case '3':
          await displayLedgerState(providers, auctionApi.deployedContract, logger);
          break;
        case '4':
          await displayPrivateState(providers, logger);
          break;
        case '5':
          displayDerivedState(currentState, logger);
          break;
        case '6':
          logger.info('Exiting...');
          return;
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* **********************************************************************
 * createWalletAndMidnightProvider: returns an object that
 * satifies both the WalletProvider and MidnightProvider
 * interfaces, both implemented in terms of the given wallet.
 */

const createWalletAndMidnightProvider = async (wallet: Wallet): Promise<WalletProvider & MidnightProvider> => {
  const state = await Rx.firstValueFrom(wallet.state());
  return {
    coinPublicKey: state.coinPublicKey,
    balanceTx(tx: UnbalancedTransaction, newCoins: CoinInfo[]): Promise<BalancedTransaction> {
      return wallet
        .balanceTransaction(
          ZswapTransaction.deserialize(tx.serialize(getLedgerNetworkId()), getZswapNetworkId()),
          newCoins,
        )
        .then((tx) => wallet.proveTransaction(tx))
        .then((zswapTx) => Transaction.deserialize(zswapTx.serialize(getZswapNetworkId()), getLedgerNetworkId()))
        .then(createBalancedTx);
    },
    submitTx(tx: BalancedTransaction): Promise<TransactionId> {
      return wallet.submitTransaction(tx);
    },
  };
};

/* **********************************************************************
 * waitForFunds: wait for tokens to appear in a wallet.
 *
 * This is an interesting example of watching the stream of states
 * coming from the pub-sub indexer.  It watches both
 *  1. how close the state is to present reality and
 *  2. the balance held by the wallet.
 */

const waitForFunds = (wallet: Wallet, logger: Logger) =>
  Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.tap((state) => {
        const scanned = state.syncProgress?.synced ?? 0n;
        const total = state.syncProgress?.total.toString() ?? 'unknown number';
        logger.info(`Wallet scanned ${scanned} blocks out of ${total}`);
      }),
      Rx.filter((state) => {
        // Let's allow progress only if wallet is close enough
        const synced = state.syncProgress?.synced ?? 0n;
        const total = state.syncProgress?.total ?? 1_000n;
        return total - synced < 100n;
      }),
      Rx.map((s) => s.balances[nativeToken()] ?? 0n),
      Rx.filter((balance) => balance > 0n),
    ),
  );

/* **********************************************************************
 * buildWalletAndWaitForFunds: the main function that creates a wallet
 * and waits for tokens to appear in it.  The various "buildWallet"
 * functions all arrive here after collecting information for the
 * arguments.
 */

const buildWalletAndWaitForFunds = async (
  { indexer, indexerWS, node, proofServer }: Config,
  logger: Logger,
  seed: string,
): Promise<Wallet & Resource> => {
  const wallet = await WalletBuilder.buildFromSeed(
    indexer,
    indexerWS,
    proofServer,
    node,
    seed,
    getZswapNetworkId(),
    'warn',
  );
  wallet.start();
  const state = await Rx.firstValueFrom(wallet.state());
  logger.info(`Your wallet seed is: ${seed}`);
  logger.info(`Your wallet address is: ${state.address}`);
  let balance = state.balances[nativeToken()];
  if (balance === undefined || balance === 0n) {
    logger.info(`Your wallet balance is: 0`);
    logger.info(`Waiting to receive tokens...`);
    balance = await waitForFunds(wallet, logger);
  }
  logger.info(`Your wallet balance is: ${balance}`);
  return wallet;
};

// Generate a random see and create the wallet with that.
const buildFreshWallet = async (config: Config, logger: Logger): Promise<Wallet & Resource> =>
  await buildWalletAndWaitForFunds(config, logger, toHex(utils.randomBytes(32)));

// Prompt for a seed and create the wallet with that.
const buildWalletFromSeed = async (config: Config, rli: Interface, logger: Logger): Promise<Wallet & Resource> => {
  const seed = await rli.question('Enter your wallet seed: ');
  return await buildWalletAndWaitForFunds(config, logger, seed);
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000042';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<(Wallet & Resource) | null> => {
  if (config instanceof StandaloneConfig) {
    return await buildWalletAndWaitForFunds(config, logger, GENESIS_MINT_WALLET_SEED);
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return await buildFreshWallet(config, logger);
      case '2':
        return await buildWalletFromSeed(config, rli, logger);
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

const mapContainerPort = (env: StartedDockerComposeEnvironment, url: string, containerName: string) => {
  const mappedUrl = new URL(url);
  const container = env.getContainer(containerName);

  mappedUrl.port = String(container.getFirstMappedPort());

  return mappedUrl.toString().replace(/\/+$/, '');
};

/* **********************************************************************
 * run: the main entry point that starts the whole bulletin board CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, logger: Logger, dockerEnv?: DockerComposeEnvironment): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  let env;
  if (dockerEnv !== undefined) {
    env = await dockerEnv.up();

    if (config instanceof StandaloneConfig) {
      config.indexer = mapContainerPort(env, config.indexer, 'auction-indexer');
      config.indexerWS = mapContainerPort(env, config.indexerWS, 'auction-indexer');
      config.node = mapContainerPort(env, config.node, 'auction-node');
      config.proofServer = mapContainerPort(env, config.proofServer, 'auction-proof-server');
    }
  }
  const wallet = await buildWallet(config, rli, logger);
  try {
    if (wallet !== null) {
      const walletAndMidnightProvider = await createWalletAndMidnightProvider(wallet);
      const providers = {
        privateStateProvider: levelPrivateStateProvider<PrivateStates>({
          privateStateStoreName: config.privateStateStoreName,
        }),
        publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
        zkConfigProvider: new NodeZkConfigProvider<'place_bid' | 'conclude_auction'>(config.zkConfigPath),
        proofProvider: httpClientProofProvider(config.proofServer),
        walletProvider: walletAndMidnightProvider,
        midnightProvider: walletAndMidnightProvider,
      };
      await mainLoop(providers, rli, logger);
    }
  } catch (e) {
    if (e instanceof Error) {
      logger.error(`Found error '${e.message}'`);
      logger.info('Exiting...');
      logger.debug(`${e.stack}`);
    } else {
      throw e;
    }
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
    } finally {
      try {
        if (wallet !== null) {
          await wallet.close();
        }
      } catch (e) {
      } finally {
        try {
          if (env !== undefined) {
            await env.down();
            logger.info('Goodbye');
            process.exit(0);
          }
        } catch (e) { }
      }
    }
  }
};
